Repository AY2223S2-CS2103-W16-2/tp, pull requests merged in 2023-04, with the labels that each got.

#217 Branch UI flaw fix
  src/main/java/seedu/techtrack/MainApp.java
  src/main/java/seedu/techtrack/logic/commands/ExitCommand.java
  src/main/java/seedu/techtrack/ui/HelpWindow.java
  src/main/java/seedu/techtrack/ui/MainWindow.java
  src/main/java/seedu/techtrack/ui/displays/RoleDisplay.java
  src/main/resources/view/TechTrackTheme.css
Labels: bug, priority.low

#218 Update salary to no allow left padding of zeroes.
  src/main/java/seedu/techtrack/model/role/Salary.java
Labels: bug

#220 Fixed UG title.
  docs/UserGuide.md
Labels: documentation

#221 Branch bug fixing
  docs/UserGuide.md
Labels: documentation

#222 Update the salary regex to only allow positive Number up to 2dp
  src/main/java/seedu/techtrack/model/role/Salary.java
Labels: bug

#223 Update the salary regex
  src/main/java/seedu/techtrack/model/role/Salary.java
Labels: bug

#224 Fixed Deadline when its is today's date and when dateline does not exist error message
  src/main/java/seedu/techtrack/logic/parser/ParserUtil.java
  src/main/java/seedu/techtrack/model/role/Deadline.java
Labels: bug

#225 Edit Command Summary
  docs/UserGuide.md
Labels: documentation

#226 Branch storage alert
  docs/UserGuide.md
  docs/images/UICommandImages/QuickStart.PNG
  src/main/java/seedu/techtrack/MainApp.java
  src/main/java/seedu/techtrack/storage/StorageManager.java
  src/main/java/seedu/techtrack/ui/MainWindow.java
  src/main/java/seedu/techtrack/ui/Ui.java
  src/main/java/seedu/techtrack/ui/UiManager.java
Labels: bug, documentation

#227 UG: Fix some bugs
  docs/UserGuide.md
  docs/images/UICommandImages/QuickStart.png
Labels: bug, documentation

#228 Branch update ppp
  docs/AboutUs.md
  docs/UserGuide.md
  docs/_data/techtrack.yml
  docs/images/UICommandImages/ViewCommand0.png
  docs/images/UICommandImages/ViewCommand1.PNG
  docs/images/UICommandImages/viewcommand.png
  docs/team/dsja612.md
  docs/team/johndoe.md
Labels: documentation

#229 Fix links in AboutUs.md
  docs/AboutUs.md
Labels: documentation

#230 Update PPP
  docs/team/dsja612.md
Labels: documentation

#233 Branch ppp
  docs/team/pzaiming.md
Labels: documentation

#234 Branch ppp
  docs/team/pzaiming.md
Labels: documentation

#235 Update PPP
  docs/team/pzaiming.md
Labels: documentation

#237 Branch ppp amoonguss
  docs/team/amoonguss1.md
Labels: documentation

#243 Fix puml diagrams and rename to rolebook
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/CompanyCommand.puml
  docs/diagrams/DeadlineCommandSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/SalaryCommandSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TagCommand.puml
Labels: documentation

#245 Update PPP
  docs/team/pzaiming.md
Labels: documentation

#247 Branch UI image fix
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/UI.png
  docs/images/Ui.png
  docs/images/startUp.png
  docs/index.md
Labels: documentation

#248 Enhance UG
  docs/UserGuide.md
Labels: documentation

#249 Branch dg
  docs/DeveloperGuide.md
  docs/images/CompanyCommandSequenceDiagram.png
Labels: documentation

#250 Fixed the filter and sort bug and update a few lines of documentation
  src/main/java/seedu/techtrack/logic/commands/DeadlineCommand.java
  src/main/java/seedu/techtrack/logic/commands/SalaryCommand.java
  src/main/java/seedu/techtrack/model/ModelManager.java
  src/main/java/seedu/techtrack/model/role/Website.java
Labels: bug, documentation

#254 [DG] Add increments to view command section and enhance formatting
  docs/DeveloperGuide.md
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ViewCommandSequenceDiagram.png
Labels: documentation

#255 Fix salary to allow input cannot be 0
  src/main/java/seedu/techtrack/model/ModelManager.java
  src/main/java/seedu/techtrack/model/role/Salary.java
Labels: bug

#268 fix most UG bugs and add more details that might deter potential bug reports
  docs/UserGuide.md
  docs/images/UICommandImages/AddCommand0.png
  docs/images/UICommandImages/DeleteCommand0.png
  docs/images/UICommandImages/DeleteCommand1.png
  docs/images/UICommandImages/EditCommand0.png
  docs/images/UICommandImages/EditCommand1.png
  docs/images/UICommandImages/NameCommand0.png
  docs/images/UICommandImages/NameCommand1.png
  docs/images/UICommandImages/ViewCommand0.png
  docs/images/UICommandImages/ViewCommand1.png
  docs/images/UICommandImages/deleteCommand.png
  docs/images/UICommandImages/editCommand.png
  docs/images/UICommandImages/helpMessage.png
  docs/images/UICommandImages/helpcommand.png
  docs/images/UICommandImages/nameCommand.png
  docs/img.png
Labels: documentation

#269 Edit puml and images
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CompanyCommand.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CompanyCommandSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#271 [DG] Updated DG
  docs/DeveloperGuide.md
Labels: documentation

#273 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#274 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#275 [DG] Update TOC automatically and new sections
  docs/DeveloperGuide.md
Labels: documentation

#276 Attempt to fix TOC in DG
  docs/DeveloperGuide.md
Labels: documentation

#278 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#279 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/DeadlineCommandSequenceDiagram.puml
  docs/diagrams/SalaryCommandSequenceDiagram.puml
  docs/images/DeadlineCommandSequenceDiagram.png
  docs/images/SalaryCommandSequenceDiagram.png
Labels: documentation

#280 Update DG
  docs/diagrams/DeadlineCommandSequenceDiagram.puml
  docs/images/DeadlineCommandSequenceDiagram.png
Labels: documentation

#281 [UG] Change TOC and standardize images
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CompanyCommand.puml
  docs/diagrams/DeadlineCommandSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/NameCommand.puml
  docs/diagrams/SalaryCommandSequenceDiagram.puml
  docs/diagrams/TagCommand.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/CompanyCommandSequenceDiagram.png
  docs/images/DeadlineCommandSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/NameCommandSequenceDiagram.png
  docs/images/SalaryCommandSequenceDiagram.png
  docs/images/TagCommandSequenceDiagram.png
  docs/images/ViewCommandSequenceDiagram.png
Labels: documentation

#282 Fix TOC
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#284 Add section to represent enhanced UI
  docs/DeveloperGuide.md
  docs/diagrams/EnhancedUIClassDiagram.puml
  docs/diagrams/MainWindowExecuteSequenceDiagram.puml
  docs/images/EnhancedUIClassDiagram.png
  docs/images/MainWindowExecuteSequenceDiagram.png
  docs/images/UICommandImages/UiEnhancement0.png
Labels: documentation

#285 Update Company Command and Delete Command
  docs/DeveloperGuide.md
  docs/diagrams/CompanyCommand.puml
  docs/images/CompanyCommandSequenceDiagram.png
Labels: documentation

#288 Branch documentation
  docs/diagrams/DeadlineCommandSequenceDiagram.puml
  docs/diagrams/SalaryCommandSequenceDiagram.puml
  docs/images/DeadlineCommandSequenceDiagram.png
  docs/images/SalaryCommandSequenceDiagram.png
Labels: documentation

#291 Branch devguide
  docs/DeveloperGuide.md
Labels: documentation

#294 Branch documentation
  docs/DeveloperGuide.md
Labels: documentation

#296 Branch documentation
  docs/DeveloperGuide.md
Labels: documentation

#299 Branch documentation
  docs/DeveloperGuide.md
Labels: documentation

#302 Branch devguide
  docs/DeveloperGuide.md
Labels: documentation

#303 [DG] Update manual testing sections
  docs/DeveloperGuide.md
Labels: documentation

#304 Updated PPP for Dylan
  docs/team/dsja612.md
Labels: documentation

#308 Edit PPP amoonguss1
  docs/team/amoonguss1.md
Labels: documentation

#309 Branch ppp
  docs/team/pzaiming.md
Labels: documentation

#310 Branch code reuse
  docs/DeveloperGuide.md
  src/main/java/seedu/techtrack/logic/commands/CommandResult.java
  src/main/java/seedu/techtrack/ui/MainWindow.java
Labels: documentation

#311 Branch documentation enhancements
  docs/DeveloperGuide.md
  docs/team/dsja612.md
Labels: documentation

#312 Compress PPP
  docs/team/dsja612.md
Labels: documentation

#314 Branch ppp
  docs/team/pzaiming.md
Labels: documentation

#317 Update PPP
  docs/team/pzaiming.md
Labels: documentation

#318 Update PPP
  docs/team/pzaiming.md
Labels: documentation

#320 Shorten PPP
  docs/team/dsja612.md
Labels: documentation

#321 Remove images not in use and fix sequence diagrams
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/NameCommand.puml
  docs/images/CommitActivityDiagram.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/LogicStorageDIP.png
  docs/images/NameCommandSequenceDiagram.png
  docs/images/SeEduLogo.png
  docs/images/findAlexDavidResult.png
  docs/images/johndoe.png
  docs/images/request_access.png
  docs/img.png
  docs/team/dsja612.md
Labels: documentation

#324 Branch ppp
  docs/team/pzaiming.md
Labels: documentation

#325 Update PPP
  docs/team/pzaiming.md
Labels: documentation
