Repository AY2223S2-CS2103-W16-2/tp, pull requests merged in 2023-03, with the labels that each got.

#30 Update README.md to point to our repo's CI
  README.md
Labels: documentation

#31 Add newline to README.md
  README.md
Labels: documentation

#56 Branch job description
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/exceptions/ParseException.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/job/JobDescription.java
  src/main/java/seedu/address/model/job/Role.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonSerializableAddressBookTest/duplicateRoleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalRolesAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRoleTest.java
  src/test/java/seedu/address/testutil/EditRoleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/RoleBuilder.java
  src/test/java/seedu/address/testutil/RoleUtil.java
  src/test/java/seedu/address/testutil/TypicalRoles.java
Labels: enhancement

#72 Fix SampleDataUtil
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: bug

#78 Rename function for displaySortedSalaryList
  src/main/java/seedu/address/logic/commands/SalaryCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SalaryCommandTest.java
Labels: priority.medium

#82 Branch UI overhaul
  docs/DevOps.md
  docs/SettingUp.md
  docs/Testing.md
  docs/team/johndoe.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/job/Company.java
  src/main/java/seedu/address/model/job/Role.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/RoleCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/TechTrack.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/RoleListCard.fxml
  src/main/resources/view/TechTrackTheme.css
  src/test/data/JsonAddressBookStorageTest/invalidAndValidRoleAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidRoleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateRoleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidRoleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalRolesAddressBook.json
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditRoleDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/job/AddressTest.java
  src/test/java/seedu/address/model/job/CompanyTest.java
  src/test/java/seedu/address/model/job/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/job/RoleTest.java
  src/test/java/seedu/address/model/job/UniqueRoleListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRoleTest.java
  src/test/java/seedu/address/testutil/EditRoleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/RoleBuilder.java
  src/test/java/seedu/address/testutil/RoleUtil.java
  src/test/java/seedu/address/testutil/TypicalRoles.java
Labels: priority.medium

#86 Updated Non-function requirement of DG
  docs/DeveloperGuide.md
Labels: documentation

#99 Branch deadline fix
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/job/Deadline.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/RoleCard.java
  src/test/java/seedu/address/model/job/DeadlineTest.java
Labels: bug, priority.High

#100 Branch documentation
  docs/DeveloperGuide.md
  docs/diagrams/SalaryCommandSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/SalaryCommand0.png
  docs/images/SalaryCommand1.png
  docs/images/SalaryCommand2.png
  docs/images/SalaryCommandSequenceDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: documentation

#102 Branch UI overhaul2
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CompanyCommand.java
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SalaryCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/job/Role.java
  src/main/java/seedu/address/ui/RoleCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/RoleListCard.fxml
  src/main/resources/view/RoleListPanel.fxml
  src/main/resources/view/TechTrackTheme.css
Labels: priority.medium

#112 Fix bug with editing JobDescription using edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: bug

#114 Branch view command v2
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CompanyCommand.java
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SalaryCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/displays/RoleDisplay.java
  src/main/java/seedu/address/ui/displays/StringDisplay.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TechTrackTheme.css
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: enhancement, priority.medium

#115 Updated welcome page in UI.
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/RoleListCard.fxml
Labels: enhancement

#118 Updated welcome page in UI.
  src/main/java/seedu/address/ui/MainWindow.java
Labels: enhancement, priority.medium

#119 Branch update ug
  docs/UserGuide.md
Labels: documentation

#120 Update Deadline Passed and UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/job/Deadline.java
Labels: priority.medium

#121 Update UG
  docs/UserGuide.md
Labels: documentation

#127 Branch UI improvements
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NameCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/NameCommandParser.java
  src/main/java/seedu/address/model/job/Role.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeadlineCommandTest.java
  src/test/java/seedu/address/logic/commands/NameCommandTest.java
  src/test/java/seedu/address/logic/commands/SalaryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/NameCommandParserTest.java
  src/test/java/seedu/address/testutil/RoleUtil.java
Labels: documentation, enhancement, priority.medium

#129 Branch update DG and landing page
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/TechTrack.png
Labels: documentation

#130 Updated index and readme
  docs/index.md
Labels: documentation

#131 Branch ug
  docs/UserGuide.md
  docs/images/CompanyCommand1.png
Labels: documentation

#147 Branch role display enhancement
  src/main/java/seedu/address/ui/displays/RoleDisplay.java
  src/main/resources/images/contact-us-96.png
  src/main/resources/images/more-details-96.png
  src/main/resources/view/TechTrackTheme.css
Labels: enhancement, priority.medium

#150 Fix PPP error
  docs/team/ryanqiu1.md
Labels: documentation

#155 Update build.gradle
  build.gradle
Labels: bug

#156 Branch view tests
  src/main/java/seedu/roles/ui/displays/RoleDisplay.java
  src/main/java/seedu/roles/ui/displays/StringDisplay.java
  src/test/java/seedu/roles/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/roles/ui/displays/RoleDisplayTest.java
  src/test/java/seedu/roles/ui/displays/StringDisplayTest.java
Labels: enhancement

#160 Branch documentation
  docs/UserGuide.md
  docs/images/DeadlineCommand0.png
  docs/images/DeadlineCommand1.png
  docs/images/DeadlineCommand2.png
  docs/images/SalaryCommand0.png
  docs/images/SalaryCommand1.png
  docs/images/SalaryCommand2.png
Labels: documentation
